name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.0.0"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter build apk --release
    - uses: softprops/action-gh-release@v1
      with:
       files: "build/app/outputs/flutter-apk/*.apk"
